/**
 * SMACNA HVAC Duct Construction Standards, Metal and Flexible, 2nd ed. (1995),
 * metric rectangular reinforcement schedules — Tables 1-3M (125 Pa), 1-4M
 * (250 Pa) and 1-5M (500 Pa), positive or negative pressure.
 *
 * GENERATED from the law.resource.org text of the standard by the research
 * scripts described in docs/hvac-duct-smacna-research.md. Do not hand-edit a
 * cell: re-run the transcription and keep the golden tests green.
 *
 * Columns are reinforcement spacings 3.0 / 2.4 / 1.8 / 1.5 / 1.2 / 0.9 / 0.75 /
 * 0.6 m. `null` is a NOT DESIGNED cell (large ducts at long spacings) or, for
 * rows with no codes at all, the NOT REQUIRED region. A `carried` cell is the
 * table's own "right-most value continues to the end of the row" rule
 * (SMACNA 1.8, p.1.13) made explicit.
 */

export type SmacnaRigidityClass = 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 'H' | 'I' | 'J' | 'K' | 'L';

export interface SmacnaReinforcementCell {
  /** Minimum rigidity class of each joint or intermediate at this spacing. */
  readonly cls: SmacnaRigidityClass;
  /** Minimum duct wall thickness (mm). */
  readonly thicknessMm: number;
  /** Class the reinforcement may be reduced to with an internal tie rod (1.10). */
  readonly tieRodClass?: SmacnaRigidityClass;
  /** Filled in by the table's continuation rule, not printed in the cell. */
  readonly carried?: true;
}

export interface SmacnaReinforcementRow {
  /** Longer-side band, inclusive (mm). */
  readonly minMm: number;
  readonly maxMm: number;
  /** Column 2: thickness at which the side needs no reinforcement (null = none given). */
  readonly unreinforcedMm: number | null;
  /** One cell per entry of SMACNA_REINFORCEMENT_SPACINGS_MM. */
  readonly cells: readonly (SmacnaReinforcementCell | null)[];
  readonly note?: string;
}

export interface SmacnaReinforcementTable {
  readonly table: '1-3M' | '1-4M' | '1-5M';
  readonly pressurePa: 125 | 250 | 500;
  readonly page: string;
  readonly rows: readonly SmacnaReinforcementRow[];
}

/** Reinforcement spacing columns, longest first (mm). */
export const SMACNA_REINFORCEMENT_SPACINGS_MM = [3000, 2400, 1800, 1500, 1200, 900, 750, 600] as const;

export const SMACNA_TABLE_1_3M: SmacnaReinforcementTable = {
  table: '1-3M',
  pressurePa: 125,
  page: 'p.1.19',
  rows: [
    { minMm: 0, maxMm: 250, unreinforcedMm: 0.55, cells: [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ] },
    { minMm: 251, maxMm: 300, unreinforcedMm: 0.55, cells: [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ] },
    { minMm: 301, maxMm: 350, unreinforcedMm: 0.55, cells: [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ] },
    { minMm: 351, maxMm: 400, unreinforcedMm: 0.55, cells: [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ] },
    { minMm: 401, maxMm: 450, unreinforcedMm: 0.55, cells: [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ] },
    { minMm: 451, maxMm: 500, unreinforcedMm: 0.70, cells: [
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'A', thicknessMm: 0.55 },
      { cls: 'A', thicknessMm: 0.55 },
    ] },
    { minMm: 501, maxMm: 550, unreinforcedMm: 0.85, cells: [
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'A', thicknessMm: 0.55 },
    ] },
    { minMm: 551, maxMm: 600, unreinforcedMm: 0.85, cells: [
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
    ] },
    { minMm: 601, maxMm: 650, unreinforcedMm: 1.00, cells: [
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
    ] },
    { minMm: 651, maxMm: 700, unreinforcedMm: 1.31, cells: [
      { cls: 'C', thicknessMm: 0.70 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
    ] },
    { minMm: 701, maxMm: 750, unreinforcedMm: 1.31, cells: [
      { cls: 'C', thicknessMm: 0.70 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
    ] },
    { minMm: 751, maxMm: 900, unreinforcedMm: 1.61, cells: [
      { cls: 'D', thicknessMm: 0.85 },
      { cls: 'D', thicknessMm: 0.70 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
    ] },
    { minMm: 901, maxMm: 1000, unreinforcedMm: null, cells: [
      { cls: 'E', thicknessMm: 1.00 },
      { cls: 'E', thicknessMm: 0.70 },
      { cls: 'D', thicknessMm: 0.70 },
      { cls: 'D', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
    ] },
    { minMm: 1001, maxMm: 1200, unreinforcedMm: null, cells: [
      { cls: 'E', thicknessMm: 1.00 },
      { cls: 'E', thicknessMm: 0.85 },
      { cls: 'E', thicknessMm: 0.70 },
      { cls: 'E', thicknessMm: 0.55 },
      { cls: 'D', thicknessMm: 0.55 },
      { cls: 'D', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
    ] },
    { minMm: 1201, maxMm: 1300, unreinforcedMm: null, cells: [
      { cls: 'F', thicknessMm: 1.31 },
      { cls: 'F', thicknessMm: 1.00 },
      { cls: 'E', thicknessMm: 0.85 },
      { cls: 'E', thicknessMm: 0.55 },
      { cls: 'E', thicknessMm: 0.55 },
      { cls: 'E', thicknessMm: 0.55 },
      { cls: 'D', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
    ] },
    { minMm: 1301, maxMm: 1500, unreinforcedMm: null, cells: [
      { cls: 'G', thicknessMm: 1.31 },
      { cls: 'F', thicknessMm: 1.00 },
      { cls: 'F', thicknessMm: 0.85 },
      { cls: 'E', thicknessMm: 0.70 },
      { cls: 'E', thicknessMm: 0.70 },
      { cls: 'E', thicknessMm: 0.55 },
      { cls: 'E', thicknessMm: 0.55 },
      { cls: 'D', thicknessMm: 0.55 },
    ] },
    { minMm: 1501, maxMm: 1800, unreinforcedMm: null, cells: [
      { cls: 'H', thicknessMm: 1.61 },
      { cls: 'H', thicknessMm: 1.31 },
      { cls: 'F', thicknessMm: 1.00 },
      { cls: 'F', thicknessMm: 0.85 },
      { cls: 'F', thicknessMm: 0.70 },
      { cls: 'E', thicknessMm: 0.70 },
      { cls: 'E', thicknessMm: 0.70 },
      { cls: 'E', thicknessMm: 0.70 },
    ] },
    { minMm: 1801, maxMm: 2100, unreinforcedMm: null, cells: [
      null,
      { cls: 'I', thicknessMm: 1.61, tieRodClass: 'G' },
      { cls: 'H', thicknessMm: 1.31, tieRodClass: 'G' },
      { cls: 'H', thicknessMm: 0.85, tieRodClass: 'G' },
      { cls: 'G', thicknessMm: 0.70 },
      { cls: 'F', thicknessMm: 0.70 },
      { cls: 'F', thicknessMm: 0.70 },
      { cls: 'F', thicknessMm: 0.70 },
    ] },
    { minMm: 2101, maxMm: 2400, unreinforcedMm: null, cells: [
      null,
      { cls: 'I', thicknessMm: 1.61, tieRodClass: 'G' },
      { cls: 'I', thicknessMm: 1.31, tieRodClass: 'G' },
      { cls: 'H', thicknessMm: 1.00, tieRodClass: 'G' },
      { cls: 'H', thicknessMm: 0.85, tieRodClass: 'G' },
      { cls: 'G', thicknessMm: 0.85 },
      { cls: 'F', thicknessMm: 0.85 },
      { cls: 'F', thicknessMm: 0.85 },
    ] },
    { minMm: 2401, maxMm: 2700, unreinforcedMm: null, cells: [
      null,
      null,
      null,
      { cls: 'I', thicknessMm: 1.31, tieRodClass: 'G' },
      { cls: 'I', thicknessMm: 1.31, tieRodClass: 'G' },
      { cls: 'H', thicknessMm: 1.31, tieRodClass: 'G' },
      { cls: 'H', thicknessMm: 1.31, tieRodClass: 'G' },
      { cls: 'G', thicknessMm: 1.31 },
    ] },
    { minMm: 2701, maxMm: 3000, unreinforcedMm: null, cells: [
      null,
      null,
      null,
      null,
      null,
      { cls: 'H', thicknessMm: 1.31, tieRodClass: 'G' },
      { cls: 'H', thicknessMm: 1.31, tieRodClass: 'G' },
      { cls: 'H', thicknessMm: 1.31, tieRodClass: 'G' },
    ] },
  ],
};

export const SMACNA_TABLE_1_4M: SmacnaReinforcementTable = {
  table: '1-4M',
  pressurePa: 250,
  page: 'p.1.21',
  rows: [
    { minMm: 0, maxMm: 250, unreinforcedMm: 0.55, cells: [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ] },
    { minMm: 251, maxMm: 300, unreinforcedMm: 0.55, cells: [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ] },
    { minMm: 301, maxMm: 350, unreinforcedMm: 0.70, cells: [
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'A', thicknessMm: 0.55 },
      { cls: 'A', thicknessMm: 0.55 },
      { cls: 'A', thicknessMm: 0.55 },
    ] },
    { minMm: 351, maxMm: 400, unreinforcedMm: 0.85, cells: [
      { cls: 'B', thicknessMm: 0.70 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'A', thicknessMm: 0.55 },
    ] },
    { minMm: 401, maxMm: 450, unreinforcedMm: 0.85, cells: [
      { cls: 'B', thicknessMm: 0.70 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
    ] },
    { minMm: 451, maxMm: 500, unreinforcedMm: 1.00, cells: [
      { cls: 'C', thicknessMm: 0.70 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
    ] },
    { minMm: 501, maxMm: 550, unreinforcedMm: 1.31, cells: [
      { cls: 'C', thicknessMm: 0.70 },
      { cls: 'C', thicknessMm: 0.70 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
    ] },
    { minMm: 551, maxMm: 600, unreinforcedMm: 1.31, cells: [
      { cls: 'C', thicknessMm: 0.70 },
      { cls: 'C', thicknessMm: 0.70 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
    ] },
    { minMm: 601, maxMm: 650, unreinforcedMm: 1.31, cells: [
      { cls: 'D', thicknessMm: 0.85 },
      { cls: 'D', thicknessMm: 0.70 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
    ] },
    { minMm: 651, maxMm: 700, unreinforcedMm: 1.61, cells: [
      { cls: 'D', thicknessMm: 0.85 },
      { cls: 'D', thicknessMm: 0.70 },
      { cls: 'D', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
    ] },
    { minMm: 701, maxMm: 750, unreinforcedMm: 1.61, cells: [
      { cls: 'E', thicknessMm: 0.85 },
      { cls: 'D', thicknessMm: 0.70 },
      { cls: 'D', thicknessMm: 0.55 },
      { cls: 'D', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
    ] },
    { minMm: 751, maxMm: 900, unreinforcedMm: null, cells: [
      { cls: 'E', thicknessMm: 1.00 },
      { cls: 'E', thicknessMm: 0.85 },
      { cls: 'E', thicknessMm: 0.70 },
      { cls: 'D', thicknessMm: 0.70 },
      { cls: 'D', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
    ] },
    { minMm: 901, maxMm: 1000, unreinforcedMm: null, cells: [
      { cls: 'F', thicknessMm: 1.31 },
      { cls: 'F', thicknessMm: 1.00 },
      { cls: 'E', thicknessMm: 0.85 },
      { cls: 'E', thicknessMm: 0.70 },
      { cls: 'E', thicknessMm: 0.55 },
      { cls: 'D', thicknessMm: 0.55 },
      { cls: 'D', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
    ] },
    { minMm: 1001, maxMm: 1200, unreinforcedMm: null, cells: [
      { cls: 'G', thicknessMm: 1.61 },
      { cls: 'G', thicknessMm: 1.31 },
      { cls: 'F', thicknessMm: 1.00 },
      { cls: 'F', thicknessMm: 0.85 },
      { cls: 'E', thicknessMm: 0.70 },
      { cls: 'E', thicknessMm: 0.55 },
      { cls: 'E', thicknessMm: 0.55 },
      { cls: 'D', thicknessMm: 0.55 },
    ] },
    { minMm: 1201, maxMm: 1300, unreinforcedMm: null, cells: [
      { cls: 'H', thicknessMm: 1.61 },
      { cls: 'H', thicknessMm: 1.31 },
      { cls: 'G', thicknessMm: 1.00 },
      { cls: 'F', thicknessMm: 0.85 },
      { cls: 'F', thicknessMm: 0.70 },
      { cls: 'E', thicknessMm: 0.70 },
      { cls: 'E', thicknessMm: 0.70 },
      { cls: 'E', thicknessMm: 0.70 },
    ] },
    { minMm: 1301, maxMm: 1500, unreinforcedMm: null, cells: [
      null,
      { cls: 'H', thicknessMm: 1.31 },
      { cls: 'G', thicknessMm: 1.00 },
      { cls: 'G', thicknessMm: 0.85 },
      { cls: 'F', thicknessMm: 0.70 },
      { cls: 'F', thicknessMm: 0.70 },
      { cls: 'E', thicknessMm: 0.70 },
      { cls: 'E', thicknessMm: 0.70 },
    ] },
    { minMm: 1501, maxMm: 1800, unreinforcedMm: null, cells: [
      null,
      null,
      { cls: 'H', thicknessMm: 1.31, tieRodClass: 'G' },
      { cls: 'H', thicknessMm: 1.31, tieRodClass: 'G' },
      { cls: 'H', thicknessMm: 0.85, tieRodClass: 'G' },
      { cls: 'F', thicknessMm: 0.70 },
      { cls: 'F', thicknessMm: 0.70 },
      { cls: 'F', thicknessMm: 0.70 },
    ] },
    { minMm: 1801, maxMm: 2100, unreinforcedMm: null, cells: [
      null,
      null,
      { cls: 'I', thicknessMm: 1.61, tieRodClass: 'G' },
      { cls: 'I', thicknessMm: 1.31, tieRodClass: 'G' },
      { cls: 'I', thicknessMm: 1.00, tieRodClass: 'G' },
      { cls: 'H', thicknessMm: 0.85, tieRodClass: 'G' },
      { cls: 'H', thicknessMm: 0.85, tieRodClass: 'G' },
      { cls: 'G', thicknessMm: 0.85 },
    ] },
    { minMm: 2101, maxMm: 2400, unreinforcedMm: null, cells: [
      null,
      null,
      null,
      { cls: 'I', thicknessMm: 1.61, tieRodClass: 'H' },
      { cls: 'I', thicknessMm: 1.31, tieRodClass: 'H' },
      { cls: 'I', thicknessMm: 1.00, tieRodClass: 'G' },
      { cls: 'H', thicknessMm: 1.00, tieRodClass: 'G' },
      { cls: 'H', thicknessMm: 0.85, tieRodClass: 'G' },
    ] },
    { minMm: 2401, maxMm: 2700, unreinforcedMm: null, cells: [
      null,
      null,
      null,
      null,
      { cls: 'I', thicknessMm: 1.31, tieRodClass: 'H' },
      { cls: 'I', thicknessMm: 1.31, tieRodClass: 'G' },
      { cls: 'I', thicknessMm: 1.31, tieRodClass: 'G' },
      { cls: 'I', thicknessMm: 1.31, tieRodClass: 'G' },
    ] },
    { minMm: 2701, maxMm: 3000, unreinforcedMm: null, cells: [
      null,
      null,
      null,
      null,
      null,
      { cls: 'I', thicknessMm: 1.31, tieRodClass: 'H' },
      { cls: 'I', thicknessMm: 1.31, tieRodClass: 'H' },
      { cls: 'I', thicknessMm: 1.31, tieRodClass: 'G' },
    ] },
  ],
};

export const SMACNA_TABLE_1_5M: SmacnaReinforcementTable = {
  table: '1-5M',
  pressurePa: 500,
  page: 'p.1.23',
  rows: [
    { minMm: 0, maxMm: 250, unreinforcedMm: 0.55, cells: [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
    ] },
    { minMm: 251, maxMm: 300, unreinforcedMm: 0.70, cells: [
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55, carried: true },
    ] },
    { minMm: 301, maxMm: 350, unreinforcedMm: 0.85, cells: [
      { cls: 'B', thicknessMm: 0.70 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.55, carried: true },
    ] },
    { minMm: 351, maxMm: 400, unreinforcedMm: 1.00, cells: [
      { cls: 'C', thicknessMm: 0.85 },
      { cls: 'C', thicknessMm: 0.70 },
      { cls: 'C', thicknessMm: 0.70 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.70 },
      { cls: 'B', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.70 },
    ] },
    { minMm: 401, maxMm: 450, unreinforcedMm: 1.00, cells: [
      { cls: 'C', thicknessMm: 0.85 },
      { cls: 'C', thicknessMm: 0.70 },
      { cls: 'C', thicknessMm: 0.70 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'B', thicknessMm: 0.70 },
    ] },
    { minMm: 451, maxMm: 500, unreinforcedMm: 1.31, cells: [
      { cls: 'C', thicknessMm: 1.00 },
      { cls: 'C', thicknessMm: 0.85 },
      { cls: 'C', thicknessMm: 0.70 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
    ] },
    { minMm: 501, maxMm: 550, unreinforcedMm: 1.61, cells: [
      { cls: 'D', thicknessMm: 1.00 },
      { cls: 'D', thicknessMm: 0.85 },
      { cls: 'D', thicknessMm: 0.70 },
      { cls: 'D', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
    ] },
    { minMm: 551, maxMm: 600, unreinforcedMm: 1.61, cells: [
      { cls: 'E', thicknessMm: 1.00 },
      { cls: 'E', thicknessMm: 0.85 },
      { cls: 'D', thicknessMm: 0.70 },
      { cls: 'D', thicknessMm: 0.55 },
      { cls: 'D', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
    ] },
    { minMm: 601, maxMm: 650, unreinforcedMm: null, cells: [
      { cls: 'E', thicknessMm: 1.00 },
      { cls: 'E', thicknessMm: 0.85 },
      { cls: 'E', thicknessMm: 0.70 },
      { cls: 'D', thicknessMm: 0.55 },
      { cls: 'D', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
    ] },
    { minMm: 651, maxMm: 700, unreinforcedMm: null, cells: [
      { cls: 'F', thicknessMm: 1.31 },
      { cls: 'E', thicknessMm: 1.00 },
      { cls: 'E', thicknessMm: 0.85 },
      { cls: 'E', thicknessMm: 0.70 },
      { cls: 'D', thicknessMm: 0.55 },
      { cls: 'D', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
    ] },
    { minMm: 701, maxMm: 750, unreinforcedMm: null, cells: [
      { cls: 'F', thicknessMm: 1.31 },
      { cls: 'F', thicknessMm: 1.00 },
      { cls: 'E', thicknessMm: 0.85 },
      { cls: 'E', thicknessMm: 0.70 },
      { cls: 'E', thicknessMm: 0.55 },
      { cls: 'D', thicknessMm: 0.55 },
      { cls: 'D', thicknessMm: 0.55 },
      { cls: 'C', thicknessMm: 0.55 },
    ] },
    { minMm: 751, maxMm: 900, unreinforcedMm: null, cells: [
      { cls: 'G', thicknessMm: 1.61 },
      { cls: 'G', thicknessMm: 1.31 },
      { cls: 'F', thicknessMm: 1.00 },
      { cls: 'F', thicknessMm: 0.85 },
      { cls: 'E', thicknessMm: 0.70 },
      { cls: 'E', thicknessMm: 0.55 },
      { cls: 'D', thicknessMm: 0.55 },
      { cls: 'D', thicknessMm: 0.55 },
    ], note: "source prints '701, 900'; band corrected to 751-900" },
    { minMm: 901, maxMm: 1000, unreinforcedMm: null, cells: [
      null,
      { cls: 'H', thicknessMm: 1.61 },
      { cls: 'G', thicknessMm: 1.31 },
      { cls: 'G', thicknessMm: 1.00 },
      { cls: 'F', thicknessMm: 0.70 },
      { cls: 'E', thicknessMm: 0.70 },
      { cls: 'E', thicknessMm: 0.55 },
      { cls: 'E', thicknessMm: 0.55 },
    ] },
    { minMm: 1001, maxMm: 1200, unreinforcedMm: null, cells: [
      null,
      { cls: 'I', thicknessMm: 1.61 },
      { cls: 'H', thicknessMm: 1.31 },
      { cls: 'H', thicknessMm: 1.00 },
      { cls: 'G', thicknessMm: 0.85 },
      { cls: 'F', thicknessMm: 0.70 },
      { cls: 'F', thicknessMm: 0.70 },
      { cls: 'E', thicknessMm: 0.70 },
    ] },
    { minMm: 1201, maxMm: 1300, unreinforcedMm: null, cells: [
      null,
      null,
      { cls: 'I', thicknessMm: 1.61, tieRodClass: 'G' },
      { cls: 'H', thicknessMm: 1.31, tieRodClass: 'G' },
      { cls: 'H', thicknessMm: 1.00, tieRodClass: 'G' },
      { cls: 'G', thicknessMm: 0.70 },
      { cls: 'F', thicknessMm: 0.70 },
      { cls: 'F', thicknessMm: 0.70 },
    ] },
    { minMm: 1301, maxMm: 1500, unreinforcedMm: null, cells: [
      null,
      null,
      { cls: 'I', thicknessMm: 1.61, tieRodClass: 'G' },
      { cls: 'H', thicknessMm: 1.31, tieRodClass: 'G' },
      { cls: 'H', thicknessMm: 1.31, tieRodClass: 'G' },
      { cls: 'G', thicknessMm: 0.85 },
      { cls: 'G', thicknessMm: 0.70 },
      { cls: 'F', thicknessMm: 0.70 },
    ] },
    { minMm: 1501, maxMm: 1800, unreinforcedMm: null, cells: [
      null,
      null,
      null,
      { cls: 'I', thicknessMm: 1.61, tieRodClass: 'H' },
      { cls: 'I', thicknessMm: 1.31, tieRodClass: 'G' },
      { cls: 'H', thicknessMm: 0.85, tieRodClass: 'G' },
      { cls: 'H', thicknessMm: 0.85, tieRodClass: 'G' },
      { cls: 'H', thicknessMm: 0.70 },
    ] },
    { minMm: 1801, maxMm: 2100, unreinforcedMm: null, cells: [
      null,
      null,
      null,
      null,
      { cls: 'J', thicknessMm: 1.31, tieRodClass: 'G' },
      { cls: 'I', thicknessMm: 1.00, tieRodClass: 'G' },
      { cls: 'I', thicknessMm: 0.85, tieRodClass: 'G' },
      { cls: 'I', thicknessMm: 0.85, tieRodClass: 'G' },
    ] },
    { minMm: 2101, maxMm: 2400, unreinforcedMm: null, cells: [
      null,
      null,
      null,
      null,
      { cls: 'J', thicknessMm: 1.31, tieRodClass: 'I' },
      { cls: 'I', thicknessMm: 1.31, tieRodClass: 'H' },
      { cls: 'I', thicknessMm: 1.00, tieRodClass: 'H' },
      { cls: 'I', thicknessMm: 0.85, tieRodClass: 'H' },
    ] },
    { minMm: 2401, maxMm: 2700, unreinforcedMm: null, cells: [
      null,
      null,
      null,
      null,
      null,
      { cls: 'K', thicknessMm: 1.31, tieRodClass: 'H' },
      { cls: 'J', thicknessMm: 1.31, tieRodClass: 'H' },
      { cls: 'I', thicknessMm: 1.31, tieRodClass: 'H' },
    ] },
    { minMm: 2701, maxMm: 3000, unreinforcedMm: null, cells: [
      null,
      null,
      null,
      null,
      null,
      null,
      { cls: 'K', thicknessMm: 1.31, tieRodClass: 'I' },
      { cls: 'J', thicknessMm: 1.31, tieRodClass: 'I' },
    ] },
  ],
};

export const SMACNA_RECTANGULAR_TABLES: readonly SmacnaReinforcementTable[] = [
  SMACNA_TABLE_1_3M,
  SMACNA_TABLE_1_4M,
  SMACNA_TABLE_1_5M,
];
